# -*- coding: utf-8 -*-

{
    'name': 'Profile PMIS',
    'version': '8.0.1.1.6',
    'sequence': 9,
    'summary': 'Project Management Information System',
    'author':   'Matmoz d.o.o., '
                'Project Expert Team',
    'contributors': [
        'Matjaž Mozetič <m.mozetic@matmoz.si>',
    ],
    'website': 'http://project.expert',
    'category': 'Project Management',
    'license': 'AGPL-3',
    'complexity': 'easy',
    'images': [],
    'depends': [
        'project_charter',
        'account_invoice_debt_start_date',
        'account_report_dept_start_date',
        'analytic_account_sequence',
        'account_analytic_lob',
        'analytic_billing_plan',
        'analytic_location',
        'analytic_resource_plan_purchase_request',
        'analytic_wip_report',
        'analytic_schedule',
        'change_management',
        'crm_change_request',
        'change_management_own_project',
        'crm_project',
        # 'crm_todo',
        'gantt_improvement',
        'hr_timesheet_product',
        'issue_change_request',
        'operations_board',
        'project_document_page',
        'project_events',
        'project_hr_stakeholder',
        'pe_project_meetings',
        'pe_project_task_issues',
        'project_time_easy_scheduling',
        'project_time_milestone',
        'project_time_schedule',
        'project_time_sequence',
        'project_wbs_task',
        'project_wbs_fancy',
        'project_wbs_gtd',
        'risk_management',
        'purchase_request_to_rfq',
        'stock_analytic_account',
        'web_sheet_full_width',
        'web_dialog_size',
        'web_export_view',
        'web_advanced_search_x2x',
        # 'analytic_line_plan_commit_hr_timesheet',
        # 'analytic_line_plan_commit_purchase',
        # 'analytic_line_plan_commit_sale',
        # 'purchase_order_analytic_search',
        # 'sale_order_line_analytic_search',
    ],
    'data': [],
    'test': [],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
